import type {
  User,
  Product,
  Supplier,
  Transaction,
  PayrollRecord,
  AttendanceRecord,
  VacationRequest,
  TimeEntry,
} from "./types"

// Mock Users
export const mockUsers: User[] = [
  {
    id: "USR-001",
    name: "Carlos Mendoza",
    email: "carlos@nuux.io",
    avatar: "/professional-man.jpg",
    role: "admin",
    permissions: [
      "god_mode",
      "view_dashboard",
      "manage_projects",
      "view_analytics",
      "manage_team",
      "manage_inventory",
      "manage_finance",
      "manage_payroll",
      "view_reports",
    ],
    department: "Dirección",
    position: "CEO",
    salary: 120000,
    hireDate: "2020-01-15",
    status: "active",
    phone: "+52 55 1234 5678",
  },
  {
    id: "USR-002",
    name: "María García",
    email: "maria@nuux.io",
    avatar: "/professional-woman-diverse.png",
    role: "manager",
    permissions: ["view_dashboard", "manage_projects", "view_analytics", "manage_team", "view_reports"],
    department: "Operaciones",
    position: "COO",
    salary: 95000,
    hireDate: "2020-03-20",
    status: "active",
    phone: "+52 55 2345 6789",
  },
  {
    id: "USR-003",
    name: "Juan Pérez",
    email: "juan@nuux.io",
    avatar: "/accountant-man.png",
    role: "accountant",
    permissions: ["view_dashboard", "manage_finance", "manage_payroll", "view_reports"],
    department: "Finanzas",
    position: "Contador Senior",
    salary: 65000,
    hireDate: "2021-06-10",
    status: "active",
    phone: "+52 55 3456 7890",
  },
  {
    id: "USR-004",
    name: "Ana López",
    email: "ana@nuux.io",
    avatar: "/stylish-woman.png",
    role: "designer",
    permissions: ["view_dashboard", "manage_projects"],
    department: "Diseño",
    position: "UX/UI Lead",
    salary: 55000,
    hireDate: "2022-01-05",
    status: "active",
    phone: "+52 55 4567 8901",
  },
  {
    id: "USR-005",
    name: "Roberto Sánchez",
    email: "roberto@nuux.io",
    avatar: "/developer-man.png",
    role: "developer",
    permissions: ["view_dashboard", "manage_projects", "view_analytics"],
    department: "Tecnología",
    position: "Full Stack Developer",
    salary: 70000,
    hireDate: "2021-09-15",
    status: "active",
    phone: "+52 55 5678 9012",
  },
  {
    id: "USR-006",
    name: "Laura Martínez",
    email: "laura@nuux.io",
    avatar: "/professional-woman-manager.png",
    role: "employee",
    permissions: ["view_dashboard", "manage_projects"],
    department: "Ventas",
    position: "Sales Representative",
    salary: 45000,
    hireDate: "2023-02-20",
    status: "vacation",
    phone: "+52 55 6789 0123",
  },
]

// Mock Products
export const mockProducts: Product[] = [
  {
    id: "PRD-001",
    sku: "LAP-MAC-001",
    name: 'MacBook Pro 14"',
    description: "Laptop Apple MacBook Pro M3 Pro",
    category: "Electrónicos",
    price: 52999,
    cost: 45000,
    quantity: 15,
    minStock: 5,
    location: "Almacén A-1",
    supplierId: "SUP-001",
    barcode: "7501234567890",
    createdAt: "2024-01-10",
    updatedAt: "2024-12-01",
    createdBy: "USR-001",
    status: "active",
  },
  {
    id: "PRD-002",
    sku: "MON-DEL-001",
    name: 'Monitor Dell 27" 4K',
    description: "Monitor Dell UltraSharp 27 4K USB-C",
    category: "Electrónicos",
    price: 12999,
    cost: 9500,
    quantity: 8,
    minStock: 3,
    location: "Almacén A-2",
    supplierId: "SUP-002",
    barcode: "7501234567891",
    createdAt: "2024-02-15",
    updatedAt: "2024-11-28",
    createdBy: "USR-001",
    status: "active",
  },
  {
    id: "PRD-003",
    sku: "KEY-LOG-001",
    name: "Teclado Logitech MX Keys",
    description: "Teclado inalámbrico premium",
    category: "Periféricos",
    price: 2499,
    cost: 1800,
    quantity: 2,
    minStock: 10,
    location: "Almacén B-1",
    supplierId: "SUP-003",
    barcode: "7501234567892",
    createdAt: "2024-03-20",
    updatedAt: "2024-12-05",
    createdBy: "USR-002",
    status: "out_of_stock",
  },
  {
    id: "PRD-004",
    sku: "MOU-LOG-001",
    name: "Mouse Logitech MX Master 3",
    description: "Mouse ergonómico avanzado",
    category: "Periféricos",
    price: 1999,
    cost: 1400,
    quantity: 25,
    minStock: 8,
    location: "Almacén B-1",
    supplierId: "SUP-003",
    barcode: "7501234567893",
    createdAt: "2024-03-20",
    updatedAt: "2024-12-03",
    createdBy: "USR-002",
    status: "active",
  },
  {
    id: "PRD-005",
    sku: "SIL-HER-001",
    name: "Silla Herman Miller Aeron",
    description: "Silla ergonómica premium",
    category: "Mobiliario",
    price: 32999,
    cost: 25000,
    quantity: 5,
    minStock: 2,
    location: "Almacén C-1",
    supplierId: "SUP-004",
    barcode: "7501234567894",
    createdAt: "2024-04-10",
    updatedAt: "2024-11-20",
    createdBy: "USR-001",
    status: "active",
  },
]

// Mock Suppliers
export const mockSuppliers: Supplier[] = [
  {
    id: "SUP-001",
    name: "Apple México",
    email: "ventas@apple.mx",
    phone: "+52 800 123 4567",
    address: "Av. Paseo de la Reforma 222, CDMX",
    contactPerson: "Ricardo Fuentes",
    products: ["PRD-001"],
    rating: 5,
    paymentTerms: "Net 30",
  },
  {
    id: "SUP-002",
    name: "Dell Technologies",
    email: "corporativo@dell.mx",
    phone: "+52 800 234 5678",
    address: "Blvd. Manuel Ávila Camacho 40, CDMX",
    contactPerson: "Patricia Vega",
    products: ["PRD-002"],
    rating: 4,
    paymentTerms: "Net 45",
  },
  {
    id: "SUP-003",
    name: "Logitech Distribuidor",
    email: "contacto@logitech-dist.mx",
    phone: "+52 800 345 6789",
    address: "Periférico Sur 4118, CDMX",
    contactPerson: "Miguel Ángel Ruiz",
    products: ["PRD-003", "PRD-004"],
    rating: 4,
    paymentTerms: "Net 30",
  },
  {
    id: "SUP-004",
    name: "Mobiliario Premium SA",
    email: "ventas@mobiliariopremium.mx",
    phone: "+52 800 456 7890",
    address: "Av. Insurgentes Sur 1647, CDMX",
    contactPerson: "Claudia Hernández",
    products: ["PRD-005"],
    rating: 5,
    paymentTerms: "Net 60",
  },
]

// Mock Transactions
export const mockTransactions: Transaction[] = [
  {
    id: "TRX-001",
    type: "income",
    category: "Ventas",
    amount: 150000,
    description: "Proyecto web cliente Acme Corp",
    date: "2024-12-01",
    reference: "INV-2024-001",
    status: "completed",
    paymentMethod: "transfer",
    userId: "USR-001",
  },
  {
    id: "TRX-002",
    type: "expense",
    category: "Nómina",
    amount: 450000,
    description: "Pago nómina Diciembre 2024",
    date: "2024-12-05",
    reference: "PAY-2024-012",
    status: "completed",
    paymentMethod: "transfer",
    userId: "USR-003",
  },
  {
    id: "TRX-003",
    type: "expense",
    category: "Servicios",
    amount: 15000,
    description: "Renta oficina Diciembre",
    date: "2024-12-01",
    reference: "RENT-2024-012",
    status: "completed",
    paymentMethod: "transfer",
    userId: "USR-003",
  },
  {
    id: "TRX-004",
    type: "income",
    category: "Consultoría",
    amount: 85000,
    description: "Consultoría estratégica Tech Solutions",
    date: "2024-12-08",
    reference: "INV-2024-002",
    status: "pending",
    paymentMethod: "transfer",
    userId: "USR-001",
  },
  {
    id: "TRX-005",
    type: "expense",
    category: "Equipamiento",
    amount: 52999,
    description: "Compra MacBook Pro desarrollo",
    date: "2024-12-03",
    reference: "PO-2024-015",
    status: "completed",
    paymentMethod: "card",
    userId: "USR-002",
  },
]

// Mock Payroll Records
export const mockPayroll: PayrollRecord[] = [
  {
    id: "PAY-001",
    userId: "USR-001",
    period: "2024-12",
    baseSalary: 120000,
    bonuses: 15000,
    deductions: 5000,
    taxes: 32500,
    netPay: 97500,
    status: "approved",
    details: [
      { concept: "Salario Base", type: "earning", amount: 120000 },
      { concept: "Bono Productividad", type: "earning", amount: 15000 },
      { concept: "IMSS", type: "deduction", amount: 5000 },
      { concept: "ISR", type: "deduction", amount: 32500 },
    ],
  },
  {
    id: "PAY-002",
    userId: "USR-002",
    period: "2024-12",
    baseSalary: 95000,
    bonuses: 10000,
    deductions: 4000,
    taxes: 25250,
    netPay: 75750,
    status: "approved",
    details: [
      { concept: "Salario Base", type: "earning", amount: 95000 },
      { concept: "Bono Liderazgo", type: "earning", amount: 10000 },
      { concept: "IMSS", type: "deduction", amount: 4000 },
      { concept: "ISR", type: "deduction", amount: 25250 },
    ],
  },
  {
    id: "PAY-003",
    userId: "USR-003",
    period: "2024-12",
    baseSalary: 65000,
    bonuses: 5000,
    deductions: 3000,
    taxes: 16750,
    netPay: 50250,
    status: "draft",
    details: [
      { concept: "Salario Base", type: "earning", amount: 65000 },
      { concept: "Bono Cierre Fiscal", type: "earning", amount: 5000 },
      { concept: "IMSS", type: "deduction", amount: 3000 },
      { concept: "ISR", type: "deduction", amount: 16750 },
    ],
  },
]

// Mock Attendance
export const mockAttendance: AttendanceRecord[] = [
  {
    id: "ATT-001",
    userId: "USR-001",
    date: "2024-12-10",
    checkIn: "08:55",
    checkOut: "18:30",
    status: "present",
    hoursWorked: 9.5,
  },
  {
    id: "ATT-002",
    userId: "USR-002",
    date: "2024-12-10",
    checkIn: "09:10",
    checkOut: "19:00",
    status: "late",
    hoursWorked: 9.8,
    notes: "Tráfico",
  },
  {
    id: "ATT-003",
    userId: "USR-003",
    date: "2024-12-10",
    checkIn: "08:45",
    checkOut: "17:30",
    status: "present",
    hoursWorked: 8.75,
  },
  {
    id: "ATT-004",
    userId: "USR-004",
    date: "2024-12-10",
    checkIn: "09:00",
    checkOut: "18:00",
    status: "present",
    hoursWorked: 9,
  },
  {
    id: "ATT-005",
    userId: "USR-005",
    date: "2024-12-10",
    checkIn: "08:30",
    checkOut: "20:00",
    status: "present",
    hoursWorked: 11.5,
  },
  { id: "ATT-006", userId: "USR-006", date: "2024-12-10", status: "vacation", hoursWorked: 0 },
]

// Mock Vacations
export const mockVacations: VacationRequest[] = [
  {
    id: "VAC-001",
    userId: "USR-006",
    type: "vacation",
    startDate: "2024-12-09",
    endDate: "2024-12-20",
    status: "approved",
    reason: "Vacaciones de fin de año",
    approvedBy: "USR-002",
  },
  {
    id: "VAC-002",
    userId: "USR-004",
    type: "personal",
    startDate: "2024-12-23",
    endDate: "2024-12-24",
    status: "pending",
    reason: "Asuntos personales",
  },
  {
    id: "VAC-003",
    userId: "USR-005",
    type: "sick",
    startDate: "2024-12-02",
    endDate: "2024-12-03",
    status: "approved",
    reason: "Consulta médica",
    approvedBy: "USR-001",
  },
]

// Mock Time Entries
export const mockTimeEntries: TimeEntry[] = [
  {
    id: "TIME-001",
    userId: "USR-004",
    projectId: "PRJ-001",
    description: "Diseño landing page",
    startTime: "09:00",
    endTime: "12:30",
    duration: 210,
    date: "2024-12-10",
    billable: true,
  },
  {
    id: "TIME-002",
    userId: "USR-005",
    projectId: "PRJ-001",
    description: "Desarrollo frontend",
    startTime: "08:30",
    endTime: "13:00",
    duration: 270,
    date: "2024-12-10",
    billable: true,
  },
  {
    id: "TIME-003",
    userId: "USR-005",
    projectId: "PRJ-002",
    description: "API integration",
    startTime: "14:00",
    endTime: "18:00",
    duration: 240,
    date: "2024-12-10",
    billable: true,
  },
  {
    id: "TIME-004",
    userId: "USR-004",
    description: "Reunión equipo",
    startTime: "14:00",
    endTime: "15:00",
    duration: 60,
    date: "2024-12-10",
    billable: false,
  },
]
