import type { CustomRole, User, Tenant } from "./types"

// Mock tenant data
export const currentTenant: Tenant = {
  id: "tenant-001",
  name: "Acme Corporation",
  slug: "acme-corp",
  plan: "enterprise",
  status: "active",
  createdAt: "2024-01-15",
  maxUsers: 50,
  features: ["custom_roles", "api_access", "white_label", "priority_support"],
  settings: {
    currency: "MXN",
    timezone: "America/Mexico_City",
    language: "es",
    fiscalYearStart: "01-01",
    allowCustomRoles: true,
    modules: ["dashboard", "projects", "analytics", "team", "inventory", "finance", "payroll", "settings", "roles"],
  },
}

// Default system roles
export const defaultRoles: CustomRole[] = [
  {
    id: "role-admin",
    tenantId: "tenant-001",
    name: "Administrador",
    description: "Acceso total al sistema. Puede gestionar todos los modulos y usuarios.",
    color: "#10B981",
    icon: "Shield",
    isSystem: true,
    isDefault: false,
    permissions: {
      dashboard: { view: true, create: true, edit: true, delete: true, export: true },
      projects: { view: true, create: true, edit: true, delete: true, export: true },
      analytics: { view: true, create: true, edit: true, delete: true, export: true },
      team: { view: true, create: true, edit: true, delete: true, export: true },
      inventory: { view: true, create: true, edit: true, delete: true, export: true },
      finance: { view: true, create: true, edit: true, delete: true, export: true },
      payroll: { view: true, create: true, edit: true, delete: true, export: true },
      settings: { view: true, create: true, edit: true, delete: true, export: true },
      roles: { view: true, create: true, edit: true, delete: true, export: true },
    },
    createdAt: "2024-01-15",
    createdBy: "system",
    updatedAt: "2024-01-15",
  },
  {
    id: "role-manager",
    tenantId: "tenant-001",
    name: "Gerente",
    description: "Gestion de equipos y proyectos. Sin acceso a configuracion del sistema.",
    color: "#3B82F6",
    icon: "UserCog",
    isSystem: true,
    isDefault: false,
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      projects: { view: true, create: true, edit: true, delete: false, export: true },
      analytics: { view: true, create: false, edit: false, delete: false, export: true },
      team: { view: true, create: true, edit: true, delete: false, export: true },
      inventory: { view: true, create: true, edit: true, delete: false, export: true },
      finance: { view: true, create: false, edit: false, delete: false, export: true },
      payroll: { view: false, create: false, edit: false, delete: false, export: false },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: true, create: false, edit: false, delete: false, export: false },
    },
    createdAt: "2024-01-15",
    createdBy: "system",
    updatedAt: "2024-01-15",
  },
  {
    id: "role-accountant",
    tenantId: "tenant-001",
    name: "Contador",
    description: "Acceso completo a finanzas y nominas. Sin acceso a otros modulos.",
    color: "#F59E0B",
    icon: "Calculator",
    isSystem: true,
    isDefault: false,
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: false },
      projects: { view: false, create: false, edit: false, delete: false, export: false },
      analytics: { view: true, create: false, edit: false, delete: false, export: true },
      team: { view: true, create: false, edit: false, delete: false, export: false },
      inventory: { view: true, create: false, edit: false, delete: false, export: true },
      finance: { view: true, create: true, edit: true, delete: true, export: true },
      payroll: { view: true, create: true, edit: true, delete: true, export: true },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
    },
    createdAt: "2024-01-15",
    createdBy: "system",
    updatedAt: "2024-01-15",
  },
  {
    id: "role-sales",
    tenantId: "tenant-001",
    name: "Ventas",
    description: "Gestion de inventario y proyectos relacionados con ventas.",
    color: "#EC4899",
    icon: "ShoppingCart",
    isSystem: false,
    isDefault: false,
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: false },
      projects: { view: true, create: true, edit: true, delete: false, export: false },
      analytics: { view: true, create: false, edit: false, delete: false, export: false },
      team: { view: true, create: false, edit: false, delete: false, export: false },
      inventory: { view: true, create: true, edit: true, delete: false, export: true },
      finance: { view: false, create: false, edit: false, delete: false, export: false },
      payroll: { view: false, create: false, edit: false, delete: false, export: false },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
    },
    createdAt: "2024-02-10",
    createdBy: "user-001",
    updatedAt: "2024-02-10",
  },
  {
    id: "role-warehouse",
    tenantId: "tenant-001",
    name: "Encargado de Almacen",
    description: "Control total del inventario y stock.",
    color: "#8B5CF6",
    icon: "Warehouse",
    isSystem: false,
    isDefault: false,
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: false },
      projects: { view: false, create: false, edit: false, delete: false, export: false },
      analytics: { view: false, create: false, edit: false, delete: false, export: false },
      team: { view: false, create: false, edit: false, delete: false, export: false },
      inventory: { view: true, create: true, edit: true, delete: true, export: true },
      finance: { view: false, create: false, edit: false, delete: false, export: false },
      payroll: { view: false, create: false, edit: false, delete: false, export: false },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
    },
    createdAt: "2024-03-05",
    createdBy: "user-001",
    updatedAt: "2024-03-05",
  },
  {
    id: "role-employee",
    tenantId: "tenant-001",
    name: "Empleado",
    description: "Acceso basico. Solo puede ver dashboard y sus proyectos asignados.",
    color: "#6B7280",
    icon: "User",
    isSystem: true,
    isDefault: true,
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: false },
      projects: { view: true, create: false, edit: false, delete: false, export: false },
      analytics: { view: false, create: false, edit: false, delete: false, export: false },
      team: { view: false, create: false, edit: false, delete: false, export: false },
      inventory: { view: false, create: false, edit: false, delete: false, export: false },
      finance: { view: false, create: false, edit: false, delete: false, export: false },
      payroll: { view: false, create: false, edit: false, delete: false, export: false },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
    },
    createdAt: "2024-01-15",
    createdBy: "system",
    updatedAt: "2024-01-15",
  },
]

// Users with role assignments
export const usersWithRoles: User[] = [
  {
    id: "user-001",
    tenantId: "tenant-001",
    name: "Carlos Martinez",
    email: "carlos@acme.com",
    avatar: "/professional-man.jpg",
    roleId: "role-admin",
    department: "Direccion",
    position: "CEO",
    salary: 85000,
    hireDate: "2020-03-15",
    status: "active",
    phone: "+52 55 1234 5678",
    lastLogin: "2024-12-10T08:30:00",
    twoFactorEnabled: true,
  },
  {
    id: "user-002",
    tenantId: "tenant-001",
    name: "Ana Rodriguez",
    email: "ana@acme.com",
    avatar: "/professional-woman-diverse.png",
    roleId: "role-manager",
    department: "Operaciones",
    position: "Gerente de Operaciones",
    salary: 55000,
    hireDate: "2021-06-01",
    status: "active",
    phone: "+52 55 2345 6789",
    lastLogin: "2024-12-10T09:15:00",
    twoFactorEnabled: true,
  },
  {
    id: "user-003",
    tenantId: "tenant-001",
    name: "Roberto Sanchez",
    email: "roberto@acme.com",
    avatar: "/accountant-man.png",
    roleId: "role-accountant",
    department: "Finanzas",
    position: "Contador Senior",
    salary: 45000,
    hireDate: "2022-01-10",
    status: "active",
    phone: "+52 55 3456 7890",
    lastLogin: "2024-12-09T17:45:00",
    twoFactorEnabled: false,
  },
  {
    id: "user-004",
    tenantId: "tenant-001",
    name: "Maria Lopez",
    email: "maria@acme.com",
    avatar: "/stylish-woman.png",
    roleId: "role-sales",
    department: "Ventas",
    position: "Ejecutiva de Ventas",
    salary: 38000,
    hireDate: "2023-03-20",
    status: "active",
    phone: "+52 55 4567 8901",
    lastLogin: "2024-12-10T10:00:00",
    twoFactorEnabled: false,
  },
  {
    id: "user-005",
    tenantId: "tenant-001",
    name: "Juan Garcia",
    email: "juan@acme.com",
    avatar: "/developer-man.png",
    roleId: "role-warehouse",
    department: "Almacen",
    position: "Jefe de Almacen",
    salary: 32000,
    hireDate: "2022-08-15",
    status: "active",
    phone: "+52 55 5678 9012",
    lastLogin: "2024-12-10T07:00:00",
    twoFactorEnabled: false,
  },
  {
    id: "user-006",
    tenantId: "tenant-001",
    name: "Laura Torres",
    email: "laura@acme.com",
    avatar: "/professional-woman-manager.png",
    roleId: "role-employee",
    department: "Marketing",
    position: "Disenadora",
    salary: 28000,
    hireDate: "2024-01-05",
    status: "active",
    phone: "+52 55 6789 0123",
    lastLogin: "2024-12-09T16:30:00",
    twoFactorEnabled: false,
  },
]
